responsive @1200px
Kiran2821996/crypto-dashboard pull request #9
Opened 2022-11-17 05:38 UTC by Kiran2821996

2022-11-17 05:49 UTC, Souvikdeb2612 requested changes

2022-11-17 05:49 UTC, Souvikdeb2612 commented on src/Components/trending/TrendItems.jsx
> +    {data.map((item, idx) => {
destructure item

2022-11-17 05:49 UTC, Souvikdeb2612 commented on src/components/trending/TrendItems.jsx
> +    {data.map((item, idx) => {
same as above

2022-11-18 13:34 UTC, Kiran2821996 commented on src/components/trending/TrendItems.jsx
> +    {data.map((item, idx) => {
data is not destructure friendly

2022-11-21 07:11 UTC, Souvikdeb2612 approved these changes

2022-11-21 07:11 UTC, merged